import { FIREBASE_API_KEY, AUTH_DOMAIN, PROJECT_ID, STORAGE_BUCKET, MESSAGING_SENDER_ID, APP_ID } from '@env';

export const CONFIG = {
  FIREBASE_API_KEY: FIREBASE_API_KEY,
  AUTH_DOMAIN: AUTH_DOMAIN,
  PROJECT_ID: PROJECT_ID,
  STORAGE_BUCKET: STORAGE_BUCKET,
  MESSAGING_SENDER_ID: MESSAGING_SENDER_ID,
  APP_ID: APP_ID,
};

console.log(FIREBASE_API_KEY);
